//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlatformHotfix
{
    
    
    [SourceAttribute("UI/BXZ/TestUI2")]
    public partial class TestUI2View
    {
        
        ComponentItemKey _componentItemKey;
        
        private UnityEngine.Transform _Transform_Background;
        
        private UnityEngine.UI.Image _Image_Image;
        
        protected ComponentItemKey componentItemKey
        {
            get
            {
			if(_componentItemKey == null) _componentItemKey = transform.GetComponent<ComponentItemKey>(); return _componentItemKey;
            }
        }
        
        protected UnityEngine.Transform Transform_Background
        {
            get
            {
				if(_Transform_Background == null)  _Transform_Background = componentItemKey.GetObject<UnityEngine.Transform>("Transform_Background"); return _Transform_Background;
            }
        }
        
        protected UnityEngine.UI.Image Image_Image
        {
            get
            {
				if(_Image_Image == null)  _Image_Image = componentItemKey.GetObject<UnityEngine.UI.Image>("Image_Image"); return _Image_Image;
            }
        }
        
        protected override void ReleaseComponent()
        {
			_Transform_Background = null;
			_Image_Image = null;
			_componentItemKey = null;
			base.ReleaseComponent();
        }
    }
}
