//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlatformHotfix
{
    using UnityEngine;
    using BUI;
    
    
    /// Generated by the MvcCreate tool,ViewComponent will be regenerated.
    [ModuleAttribute("Test")]
    [MvcAttribute("TestUI2")]
    public partial class TestUI2View : View
    {
        protected override void Init(object data)
        {
        }
    }
}
